apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kind-test-wge-2
  namespace: wego-system
resources:
- weave-gitops-enterprise.yaml
- gitops-runtime.yaml
- flux-source-resource.yaml
- flux-system-kustomization-resource.yaml
- flux-user-kustomization-resource.yaml
