apiVersion: apps/v1
kind: Deployment
metadata:
  name: wego-app
  namespace: wego-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wego-app
    spec:
      serviceAccountName: wego-app-service-account
      containers:
        - name: wego-app
          image: ghcr.io/weaveworks/wego-app:0.6.2
          args: ["ui", "run", "-l", "--helm-repo-namespace", "wego-system"]
          ports:
            - containerPort: 9001
              protocol: TCP
          imagePullPolicy: IfNotPresent
  selector:
    matchLabels:
      app: wego-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wego-helm-watcher-role
rules:
  - apiGroups:
      - source.toolkit.fluxcd.io
    resources:
      - helmrepositories
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - source.toolkit.fluxcd.io
    resources:
      - helmrepositories/finalizers
    verbs:
      - create
      - delete
      - get
      - patch
      - update
  - apiGroups:
      - source.toolkit.fluxcd.io
    resources:
      - helmrepositories/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wego-helm-watcher-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wego-helm-watcher-role
subjects:
  - kind: ServiceAccount
    name: wego-app-service-account
    namespace: wego-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-resources
  namespace: wego-system
subjects:
  - kind: ServiceAccount
    name: wego-app-service-account
    namespace: wego-system
roleRef:
  kind: Role
  name: resources-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: resources-reader
  namespace: wego-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","create"]
  - apiGroups: ["wego.weave.works"]
    resources: [ "apps" ]
    verbs: [ "*" ]
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: [ "kustomizations" ]
    verbs: [ "*" ]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: [ "helmreleases" ]
    verbs: [ "*" ]
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: [ "helmrepositories" ]
    verbs: [ "*" ]
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: [ "gitrepositories" ]
    verbs: [ "*" ]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wego-app-service-account
  namespace: wego-system
secrets:
  - name: wego-app-service-account-token
---
apiVersion: v1
kind: Service
metadata:
  name: wego-app
  namespace: wego-system
spec:
  selector:
    app: wego-app
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
