apiVersion: v1
data:
  config: |
    ConfigRepo: ssh://git@github.com/nikimanoledaki/fun-times.git
    FluxNamespace: wego-system
    WegoNamespace: wego-system
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: weave-gitops-config
  namespace: wego-system
